#+PROPERTY: header-args :results silent :comments link :mkdirp yes :eval no :tangle ../../resources/site-start.el

#+TITLE: Emacs Site Start Init Script

The =site-start.el= script is used by =weborg= to configure the Emacs instance
that is started from the command line.

* use-package

This code snipped is used to make sure that =use-package= is installed and
availble to Emacs. Once it is installed, the package is required such that we
can use it to use all other required packages.

#+begin_src elisp
(require 'package)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package)
  (eval-when-compile
    (unless (bound-and-true-p package--initialized)
      (package-initialize))  ;; be sure load-path includes package directories
    (require 'use-package)))
#+end_src

* Use Packages

Series of package that are enabled. Those are the default ones shipped with
=weborg=. If you are using a new language that is not currently supported by any
of the major mode listed below, yhou will have to:

  1. install it in =install.org=
  2. use it below
  3. delete the Docker image in the current environment
  4. run =weborg= to have it recreating the image with the new supported mode

If you don't add the new major mode in Emacs, Org-mode will complain that it
doesn't know how to handle comments for that language, and won't tangle the Org
file where the code block that uses this language is located.

#+begin_src elisp
(use-package org)
(use-package dockerfile-mode)
(use-package yaml-mode)
(use-package terraform-mode)
(use-package graphviz-dot-mode)
(use-package plantuml-mode)
(use-package toml-mode)
#+end_src

* Configure PlantUML

Configure [[https://plantuml.com][PlantUML]] such that we can create helpful diagram and to =weborg
execute= their code blocks to generate the images of the diagrams.

#+begin_src elisp
(setq plantuml-jar-path "/usr/bin/plantuml")
(setq org-plantuml-executable-path "/usr/bin/plantuml")
(setq plantuml-default-exec-mode 'executable)
(setq org-plantuml-exec-mode 'plantuml)
#+end_src

* Configure Org-babel

Load languages for Org major mode. Those are used when executing a Org file (not
when tangling nor weaving it).

If you don't *execute* code blocks with any new major mode you may install, you
*do not* need to add it to that list.

#+begin_src elisp
(org-babel-do-load-languages
  'org-babel-load-languages
  '((emacs-lisp . t)
    (python . t)
    (dot . t)
    (plantuml . t)))
#+end_src

* Disable Backup Files

Disable backup files. They are not needed in this context since all the process
is automated. The added benefit is that it won't make =monitoring= going crazy.

#+begin_src elisp
(setq make-backup-files nil)
#+end_src

* Configure python-mode

=python-mode= configurations to properly handle indentation between =tangling=
and =detangling= of files.

Note: those configurations assumes that all code processed by =weborg= uses
spaces for indentation instead of tabs.

#+begin_src elisp
(custom-set-variables
 '(indent-tabs-mode nil)
 '(python-indent-guess-indent-offset t)
 '(python-indent-guess-indent-offset-verbose nil)
 '(org-edit-src-content-indentation 0))
#+end_src
